version: '3.8'

services:
 
  # Service untuk Redis
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - be_network

 # Service untuk aplikasi Express
  app:
    build: .
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb+srv://nestamaulana09:4WbOmNUwLmq13Uhk@dbnestabetest.zfqy9ez.mongodb.net/DB_NestaMaulana_Test?retryWrites=true&w=majority&appName=dbnestabetest
      # Tambahkan variabel lingkungan lainnya yang diperlukan untuk proyek Anda
    depends_on:
      - redis
    networks:
      - be_network

networks: 
  be_network: